/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pricing_user;

import java.io.*;
import java.util.Random;
import java.net.*;
import javax.swing.JOptionPane;
/**
 *
 * @author egc
 */
public class Selectplan extends javax.swing.JFrame {

    /**
     * Creates new form Selectplan
     */
   Socket socket;
    public Selectplan() {
        initComponents();
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT THE USAGE PLANS FOR SNESOR CLOUD");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 60, 500, 52);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricing_user/images/services-banner.jpg"))); // NOI18N
        jLabel12.setText(" ");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 0, 753, 167);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        jLabel3.setText("SENSOR DATA TYPE ");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(250, 230, 140, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        jLabel4.setText("TIME ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(350, 310, 38, 24);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        jLabel5.setText("SPACE");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(340, 380, 50, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WEATHER REPORT", "TRAFFIC REPORT", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(460, 230, 275, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 MINS", "1 HOUR", "LEASE FOR 1 YEAR", " " }));
        jComboBox3.setName(""); // NOI18N
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(460, 300, 275, 27);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100GB", "500GB", "1 TB", " " }));
        jPanel4.add(jComboBox4);
        jComboBox4.setBounds(460, 380, 274, 28);

        jButton1.setFont(new java.awt.Font("Lucida Console", 2, 14)); // NOI18N
        jButton1.setText("REQUEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(530, 440, 125, 32);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricing_user/images/images.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 190, 230, 290);

        jButton2.setFont(new java.awt.Font("Lucida Console", 2, 14)); // NOI18N
        jButton2.setText("Plan Rates");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(340, 440, 140, 30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String data = jComboBox2.getSelectedItem().toString();
        
        
        String Time = jComboBox3.getSelectedItem().toString();
        String space = jComboBox4.getSelectedItem().toString();
      
       try
        {
            String host = "localhost";
            int port = 25000;
            InetAddress address = InetAddress.getByName(host);
           socket = new Socket(address, port);
 
            //Send the message to the server
            OutputStream os = socket.getOutputStream();
            OutputStreamWriter osw = new OutputStreamWriter(os);
            BufferedWriter bw = new BufferedWriter(osw);
      
            String sendMessage = data+"\n";
            bw.write(sendMessage);
         
            bw.flush();
           
            System.out.println("Message sent to the server : "+sendMessage);
            
            
            //Get the return message from the server
            InputStream is = socket.getInputStream();
            InputStreamReader isr = new InputStreamReader(is);
            BufferedReader br = new BufferedReader(isr);
            String message = br.readLine();
            System.out.println("Message received from the server : " +message);
            
            bw.close();
            socket.close();
            JOptionPane.showMessageDialog(this, message);
        }
        catch (Exception e)
        {
        }
        
        new DATA_STORE(data, Time, space).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        plan_rate pr = new plan_rate();
        pr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
