/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pricing_user;

//import data_owner.Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pricing_user.Login;

/**
 *
 * @author egc
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection conn;
    Statement stmt;
    ResultSet rs;
    public signup() {
        initComponents();
          try {
            String url = "jdbc:mysql://localhost:3307/";   
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver);   
            conn = DriverManager.getConnection(url +"sensor","root","");     
            stmt = conn.createStatement();
            System.out.println("connected successfully");    
         } catch (Exception e) {
            System.out.println(e.getMessage());    
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel9.setText("USER-SIGNUP");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 60, 200, 40);

        jLabel1.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jLabel1.setText("USER-NAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(417, 225, 88, 23);

        jTextField1.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(575, 225, 171, 30);

        jLabel2.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(417, 276, 78, 17);

        jTextField2.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(575, 270, 171, 30);

        jButton1.setFont(new java.awt.Font("Franklin Gothic Book", 2, 14)); // NOI18N
        jButton1.setText("SIGN-UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(482, 408, 83, 25);

        jButton2.setFont(new java.awt.Font("Franklin Gothic Book", 2, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jPanel2.add(jButton2);
        jButton2.setBounds(575, 408, 73, 25);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricing_user/images/images.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 173, 380, 283);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricing_user/images/services-banner.jpg"))); // NOI18N
        jLabel4.setText(" ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 810, 145);

        jLabel5.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jLabel5.setText("NAME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(417, 174, 88, 23);

        jTextField3.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jPanel2.add(jTextField3);
        jTextField3.setBounds(575, 174, 171, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pricing_user/images/WireStentDemot2Step01.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(81, 146, 613, 9);

        jLabel7.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jLabel7.setText("CONFIRM-PASSWORD");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(417, 311, 148, 26);

        jTextField4.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jPanel2.add(jTextField4);
        jTextField4.setBounds(575, 313, 171, 30);

        jLabel8.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jLabel8.setText("E-MAIL");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(416, 364, 148, 26);

        jTextField5.setFont(new java.awt.Font("Gisha", 2, 14)); // NOI18N
        jPanel2.add(jTextField5);
        jTextField5.setBounds(574, 366, 172, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String sql;
        String suname,spass,sname,semail;
       
        sname = jTextField3.getText();
        suname = jTextField1.getText();
        spass = jTextField2.getText();
        semail = jTextField5.getText();
        
        sql = ("INSERT INTO `user`(`name`, `uname`, `pass`, `email`) VALUES ('"+sname+"','"+suname+"','"+spass+"','"+semail+"');");
        
        try {
            stmt.executeUpdate(sql);
            
        } catch (SQLException ex) {
           
        }
        JOptionPane.showMessageDialog(this, "Registration Success");
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
